### ISSUE TITLE
[Mythical Game | Leaderboard] Game Event Point

### ISSUE THREAD

**Issue by saltict** [Koniverse/PlaynationAPI#38]
- [x] Add game event point type CMS, with filter events by some props
- [x] Add game event point API

**Comment by anhntk54** [comment]
- Game event add field type 
- Add type leaderboard and metric achievement: mythical-game:event:point
- Add field gameEventTypes leaderboard and metric achievement filter data leaderboard with type of Game event

**Comment by Sokol142196** [comment]
Validation passed in cases:
- Check setup
- Check task 
- Check leaderboard
